FROM quay.io/lnxjedi/gopherbot-base:latest

ENV NODE_VERSION 12.21.0
ENV YARN_VERSION 1.22.10
ENV ARCH x64

## Install nodejs, npm and yarn
## Refresh from https://github.com/nodejs/docker-node/blob/master/12/buster/Dockerfile
RUN ARCH=${ARCH} \
  # gpg keys listed at https://github.com/nodejs/node#release-keys
  && set -ex \
  && for key in \
    4ED778F539E3634C779C87C6D7062848A1AB005C \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    74F12602B6F1C4E913FAA37AD3A89613643B6201 \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
    108F52B48DB57BB0CC439B2997B01419BD92F80A \
    B9E2F5981AA6E0CD28160D9FF13993A75599653C \
  ; do \
    gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
    gpg --batch --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
    gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
  done \
  && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
  && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
  # smoke tests
  && node --version \
  && npm --version

RUN set -ex \
  && for key in \
    6A010C5166006599AA17F08146C2130DFD2497F5 \
  ; do \
    gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
    gpg --batch --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
    gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
  done \
  && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
  && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc" \
  && gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
  && mkdir -p /opt \
  && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
  && rm yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
  # smoke test
  && yarn --version

ARG THEIA_VERSION=latest
ARG THEIA_HOME=/usr/local/theia

WORKDIR ${THEIA_HOME}
## Refresh from: https://raw.githubusercontent.com/theia-ide/theia-apps/master/theia-full-docker/latest.package.json
## Note: all references to 'php' scrubbed, to prevent noise message on startup.
## Note: applicationName set to "Theia Gopherbot Devel Interface"
ADD ${THEIA_VERSION}.package.json ./package.json
RUN chmod 0755 ${THEIA_HOME} && \
  yarn --pure-lockfile && \
  NODE_OPTIONS="--max_old_space_size=4096" yarn theia build && \
  yarn theia download:plugins && \
  yarn --production && \
  yarn autoclean --init && \
  echo *.ts >> .yarnclean && \
  echo *.ts.map >> .yarnclean && \
  echo *.spec.* >> .yarnclean && \
  yarn autoclean --force && \
  yarn cache clean && \
  chown -R ${USER}:${USER} ${HOME}

USER ${USER}:${USER}
RUN go get -u -v golang.org/x/tools/gopls && \
  go get -u -v github.com/uudashr/gopkgs/v2/cmd/gopkgs && \
  go get -u -v github.com/ramya-rao-a/go-outline && \
  go get -u -v github.com/acroca/go-symbols && \
  go get -u -v golang.org/x/tools/cmd/guru && \
  go get -u -v golang.org/x/tools/cmd/gorename && \
  go get -u -v github.com/cweill/gotests/... && \
  go get -u -v github.com/fatih/gomodifytags && \
  go get -u -v github.com/josharian/impl && \
  go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct && \
  go get -u -v github.com/haya14busa/goplay/cmd/goplay && \
  go get -u -v github.com/godoctor/godoctor && \
  go get -u -v github.com/go-delve/delve/cmd/dlv && \
  go get -u -v github.com/stamblerre/gocode && \
  go get -u -v github.com/rogpeppe/godef && \
  go get -u -v github.com/sqs/goreturns && \
  go get -u -v golang.org/x/lint/golint && \
  go get -u -v golang.org/x/tools/cmd/goimports && \
  python3 -m pip install -U pylint --user && \
  ln ${HOME}/go/bin/gocode ${HOME/go/bin/gocode-gomod} && \
  rm -rf ${HOME}/.cache ${HOME}/go/src
USER root:root

# TODO: Remove this later, it's an UGLY HACK for Theia's odd
# PATH munging.
RUN ln /usr/bin/groups /usr/local/go/bin/groups

ENV SHELL=/bin/bash \
  THEIA_DEFAULT_PLUGINS=local-dir:/usr/local/theia/plugins \
  USE_LOCAL_GIT=true
