FROM node:12-bullseye

RUN apt-get update && apt-get install -y libsecret-1-dev
WORKDIR /usr/local/theia
# From https://github.com/theia-ide/theia-apps/tree/master/theia-python-docker;
# modified applicationName "Theia Gopherbot IDE"
ADD latest.package.json ./package.json
RUN yarn --pure-lockfile && \
    NODE_OPTIONS="--max_old_space_size=4096" yarn theia build && \
    yarn theia download:plugins && \
    yarn --production && \
    yarn autoclean --init && \
    echo *.ts >> .yarnclean && \
    echo *.ts.map >> .yarnclean && \
    echo *.spec.* >> .yarnclean && \
    yarn autoclean --force && \
    yarn cache clean

FROM node:12-bullseye

# Package for ruby & python extension development
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    bind9-dnsutils \
    jq \
    python3-dev \
    python3-pip \
    ruby \
    vim && \
  pip3 install \
    autopep8 \
    flake8 \
    pylint \
    python-language-server && \
  gem install \
    irb && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /tmp/*

RUN useradd -d /var/lib/robot -r -c "Gopherbot Robot" robot && \
  mkdir -p /var/lib/robot && \
  chown robot:robot /var/lib/robot && \
  chmod 0755 /var/lib/robot

WORKDIR /usr/local/theia
COPY --from=0 /usr/local/theia /usr/local/theia
EXPOSE 3000

# configure Theia
ENV SHELL=/bin/bash \
    THEIA_DEFAULT_PLUGINS=local-dir:/usr/local/theia/plugins

ENTRYPOINT [ "node", "/usr/local/theia/src-gen/backend/main.js", "/var/lib/robot", "--hostname=0.0.0.0" ]
