FROM mirror.gcr.io/library/ubuntu:latest

ARG username=robot
ARG userid=1000
ARG nonprivuser=nobody

ARG homedir=/home/robot

ARG goversion=1.15.8

ENV HOME=${homedir}
ENV PATH=${PATH}:${HOME}/go/bin:${HOME}/.local/bin:/usr/local/go/bin:/opt/gopherbot
ENV USER=${username}
ENV USERID=${userid}

RUN useradd -d ${homedir} -m -u ${userid} ${username}

# Add a random UUID to avoid using the cache for desired updates,
# thanks to https://www.uuidgenerator.net
ADD https://www.uuidgenerator.net/api/version4 /uuid
#ADD http://worldtimeapi.org/api/timezone/Etc/UTC /timestamp
ADD http://worldclockapi.com/api/json/utc/now /timestamp

RUN chown ${username}:${username} /uuid /timestamp && \
  chmod 644 /uuid /timestamp

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    bind9-dnsutils \
    curl \
    g++ \
    gcc \
    git \
    jq \
    make \
    openssh-client \
    python3 \
    python3-pip \
    ruby \
    unzip \
    vim \
    zip && \
  rm -rf /var/lib/apt/lists/*

RUN cd /usr/local && \
  curl -L https://dl.google.com/go/go${goversion}.linux-amd64.tar.gz | tar xzf -
