name: build-base-containers

on:
  workflow_dispatch:
  schedule:
  # Early Monday
  - cron: '7 2 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: "lnxjedi+autobuild"
          password: ${{ secrets.QUAY_LNXJEDI_TOKEN }}
      -
        name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: base/
          file: base/Containerfile
          push: true
          tags: quay.io/lnxjedi/gopherbot-base:latest
      -
        name: Build and push theia
        uses: docker/build-push-action@v2
        with:
          context: theia/
          file: theia/Containerfile
          push: true
          tags: quay.io/lnxjedi/gopherbot-base-theia:latest
